# Generated by Django 2.2.1 on 2019-10-28 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=1024, verbose_name='File Image Name')),
                ('file', models.CharField(default='static/content', max_length=1024, verbose_name='File Location')),
                ('uploadDate', models.DateTimeField(verbose_name='Upload Date')),
                ('startDate', models.DateTimeField(verbose_name='Start Date')),
                ('expireDate', models.DateTimeField(verbose_name='Expire Date')),
                ('displayTime', models.IntegerField(default=5, verbose_name='Display Time (Seconds)')),
                ('gifIteration', models.IntegerField(default=1, verbose_name='GIF repeat count')),
                ('order', models.CharField(default='-1', max_length=255, verbose_name='Special Order')),
                ('useInShow', models.BooleanField(default=False, verbose_name='Use in Show')),
                ('deleteOnExpire', models.BooleanField(default=True, verbose_name='Delete on Expire')),
            ],
        ),
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvName', models.CharField(max_length=200, verbose_name='Name')),
                ('hostIP', models.CharField(default='192.168.0.X', max_length=2000, verbose_name='Host Addr. or IP:')),
                ('width', models.IntegerField(default=1920, verbose_name='Screen Width')),
                ('height', models.IntegerField(default=1080, verbose_name='Screen Height')),
                ('key', models.CharField(default='FILL', max_length=48, verbose_name='Key')),
                ('useSchedule', models.BooleanField(default=False, verbose_name='Use Schedule')),
                ('startTime', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='TV On Time')),
                ('endTime', models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='TV On Time')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Slide Show Name', max_length=255, verbose_name='Show Name')),
                ('file', models.CharField(default='static/shows', max_length=255, verbose_name='File Location')),
            ],
        ),
    ]
