# Generated by Django 2.2.1 on 2019-07-17 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_auto_20190717_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='show',
        ),
    ]
