# Generated by Django 2.2.1 on 2019-07-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_remove_content_show'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='show',
            name='name',
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Show ID'),
        ),
    ]
