# Generated by Django 2.2.1 on 2019-08-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_auto_20190717_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='deleteOnExpire',
            field=models.BooleanField(default=True, verbose_name='Delete on Expire'),
        ),
        migrations.AddField(
            model_name='content',
            name='useInShow',
            field=models.BooleanField(default=False, verbose_name='Use in Show'),
        ),
    ]
