# Generated by Django 2.2.1 on 2019-08-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_auto_20190810_0517'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='name',
            field=models.CharField(default='Slide Show Name', max_length=150, verbose_name='Show Name'),
        ),
        migrations.AlterField(
            model_name='show',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
