# Generated by Django 2.2.1 on 2019-08-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_auto_20190813_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='file',
            field=models.CharField(default='static/content', max_length=1024, verbose_name='File Location'),
        ),
        migrations.AlterField(
            model_name='content',
            name='imageName',
            field=models.CharField(max_length=1024, verbose_name='File Image Name'),
        ),
        migrations.AlterField(
            model_name='show',
            name='name',
            field=models.CharField(default='Slide Show Name', max_length=255, verbose_name='Show Name'),
        ),
    ]
