# Generated by Django 2.2.1 on 2019-09-02 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20190820_0737'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvName', models.CharField(max_length=200, verbose_name='Name')),
                ('HostIP', models.CharField(default='192.168.0.X', max_length=2000, verbose_name='Host Addr. or IP:')),
            ],
        ),
        migrations.AddField(
            model_name='show',
            name='file',
            field=models.CharField(default='static/shows', max_length=255, verbose_name='File Location'),
        ),
    ]
