# Generated by Django 2.2.1 on 2019-09-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_auto_20190902_0753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Screens',
            new_name='Screen',
        ),
    ]
