# Generated by Django 2.2.1 on 2019-09-18 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_auto_20190902_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='key',
            field=models.CharField(default='FILL', max_length=512, verbose_name='Key'),
        ),
        migrations.AlterField(
            model_name='content',
            name='displayTime',
            field=models.IntegerField(default=5, verbose_name='Display Time (Seconds)'),
        ),
    ]
