# Generated by Django 2.2.1 on 2019-09-21 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_auto_20190918_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='screen',
            name='key',
            field=models.CharField(default='FILL', max_length=48, verbose_name='Key'),
        ),
    ]
