# Generated by Django 2.2.1 on 2019-10-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0014_auto_20190921_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='gifIteration',
            field=models.IntegerField(default=1, verbose_name='GIF repeat count'),
        ),
    ]
